del ..\docbook\e-template.xml
del ..\docbook\perspective.xml
del ..\docbook\perspective-readme.xml
del ..\docbook\tropical.xml
del ..\site\e-template.html
del ..\site\perspective.html
del ..\site\perspective-readme.html
del ..\site\tropical.html
del ..\site\e-template.htm
del ..\site\perspective.htm
del ..\site\perspective-readme.htm
del ..\site\tropical.htm
del ..\site\pdf\e-template.fo
del ..\site\pdf\perspective.fo
del ..\site\pdf\perspective-readme.fo
del ..\site\pdf\tropical.fo
del ..\site\pdf\e-template.pdf
del ..\site\pdf\perspective.pdf
del ..\site\pdf\perspective-readme.pdf
del ..\site\pdf\tropical.pdf
