tclsh85 ..\scripts\tcmd.tcl -validate e-template
tclsh85 ..\scripts\tcmd.tcl -docbook e-template
tclsh85 ..\scripts\tcmd.tcl -dbvalidate e-template
tclsh85 ..\scripts\tcmd.tcl -html e-template
tclsh85 ..\scripts\tcmd.tcl -web e-template
tclsh85 ..\scripts\tcmd.tcl -fo e-template
tclsh85 ..\scripts\tcmd.tcl -pdf e-template
tclsh85 ..\scripts\tcmd.tcl -validate perspective
tclsh85 ..\scripts\tcmd.tcl -docbook perspective
tclsh85 ..\scripts\tcmd.tcl -dbvalidate perspective
tclsh85 ..\scripts\tcmd.tcl -html perspective
tclsh85 ..\scripts\tcmd.tcl -web perspective
tclsh85 ..\scripts\tcmd.tcl -fo perspective
tclsh85 ..\scripts\tcmd.tcl -pdf perspective
tclsh85 ..\scripts\tcmd.tcl -validate perspective-readme
tclsh85 ..\scripts\tcmd.tcl -docbook perspective-readme
tclsh85 ..\scripts\tcmd.tcl -dbvalidate perspective-readme
tclsh85 ..\scripts\tcmd.tcl -html perspective-readme
tclsh85 ..\scripts\tcmd.tcl -web perspective-readme
tclsh85 ..\scripts\tcmd.tcl -fo perspective-readme
tclsh85 ..\scripts\tcmd.tcl -pdf perspective-readme
tclsh85 ..\scripts\tcmd.tcl -validate tropical
tclsh85 ..\scripts\tcmd.tcl -docbook tropical
tclsh85 ..\scripts\tcmd.tcl -dbvalidate tropical
tclsh85 ..\scripts\tcmd.tcl -html tropical
tclsh85 ..\scripts\tcmd.tcl -web tropical
tclsh85 ..\scripts\tcmd.tcl -fo tropical
tclsh85 ..\scripts\tcmd.tcl -pdf tropical
