tclsh ..\scripts\tcmd.tcl -validate e-template
tclsh ..\scripts\tcmd.tcl -docbook e-template
tclsh ..\scripts\tcmd.tcl -dbvalidate e-template
tclsh ..\scripts\tcmd.tcl -html e-template
tclsh ..\scripts\tcmd.tcl -web e-template
tclsh ..\scripts\tcmd.tcl -fo e-template
tclsh ..\scripts\tcmd.tcl -pdf e-template
tclsh ..\scripts\tcmd.tcl -validate perspective
tclsh ..\scripts\tcmd.tcl -docbook perspective
tclsh ..\scripts\tcmd.tcl -dbvalidate perspective
tclsh ..\scripts\tcmd.tcl -html perspective
tclsh ..\scripts\tcmd.tcl -web perspective
tclsh ..\scripts\tcmd.tcl -fo perspective
tclsh ..\scripts\tcmd.tcl -pdf perspective
tclsh ..\scripts\tcmd.tcl -validate perspective-readme
tclsh ..\scripts\tcmd.tcl -docbook perspective-readme
tclsh ..\scripts\tcmd.tcl -dbvalidate perspective-readme
tclsh ..\scripts\tcmd.tcl -html perspective-readme
tclsh ..\scripts\tcmd.tcl -web perspective-readme
tclsh ..\scripts\tcmd.tcl -fo perspective-readme
tclsh ..\scripts\tcmd.tcl -pdf perspective-readme
tclsh ..\scripts\tcmd.tcl -validate tropical
tclsh ..\scripts\tcmd.tcl -docbook tropical
tclsh ..\scripts\tcmd.tcl -dbvalidate tropical
tclsh ..\scripts\tcmd.tcl -html tropical
tclsh ..\scripts\tcmd.tcl -web tropical
tclsh ..\scripts\tcmd.tcl -fo tropical
tclsh ..\scripts\tcmd.tcl -pdf tropical
