#!/bin/bash
../scripts/tcmd.tcl -validate e-template
../scripts/tcmd.tcl -docbook e-template
../scripts/tcmd.tcl -dbvalidate e-template
../scripts/tcmd.tcl -html e-template
../scripts/tcmd.tcl -web e-template
../scripts/tcmd.tcl -fo e-template
../scripts/tcmd.tcl -pdf e-template
../scripts/tcmd.tcl -validate perspective
../scripts/tcmd.tcl -docbook perspective
../scripts/tcmd.tcl -dbvalidate perspective
../scripts/tcmd.tcl -html perspective
../scripts/tcmd.tcl -web perspective
../scripts/tcmd.tcl -fo perspective
../scripts/tcmd.tcl -pdf perspective
../scripts/tcmd.tcl -validate perspective-readme
../scripts/tcmd.tcl -docbook perspective-readme
../scripts/tcmd.tcl -dbvalidate perspective-readme
../scripts/tcmd.tcl -html perspective-readme
../scripts/tcmd.tcl -web perspective-readme
../scripts/tcmd.tcl -fo perspective-readme
../scripts/tcmd.tcl -pdf perspective-readme
../scripts/tcmd.tcl -validate tropical
../scripts/tcmd.tcl -docbook tropical
../scripts/tcmd.tcl -dbvalidate tropical
../scripts/tcmd.tcl -html tropical
../scripts/tcmd.tcl -web tropical
../scripts/tcmd.tcl -fo tropical
../scripts/tcmd.tcl -pdf tropical
